### ISSUE TITLE
Support for redis sentinel

### ISSUE THREAD

**Issue by davehorton** [jambonz/realtimedb-helpers#42]
For high availability, this package should optionally support connecting to a redis cluster using [redis sentinel](https://redis.io/docs/management/sentinel/).  Of course, this change must be backwards compatible so that installs can continue choosing to connect to a single redis server using the existing env vars.  

In order to support redis sentinel, I believe we will need to remove the dependency on the 'redis' npm package in favor or using [ioredis](https://www.npmjs.com/package/ioredis).  (Note that ioredis supports Promises natively so this should actually clean up/simplify some of our code).

**Comment by davehorton** [comment]
Note: following this change it will also be necessary to make similar changes in any other jambonz apps or packages where we are accessing redis directly; however this is the repo with the most changes and is easily tested so let's do this first

**Comment by xquanluu** [comment]
PR merged and all related product already used latest release, closing this issue
